language: c
sudo: required
script: ./tests/travis-run.sh

cache:
  directories:
  - $HOME/.opam
  - /usr/local

env:
  # - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02

os:
  - linux
#  - osx

# BCP and brabalan, 1/19: We took away the OSX build because it is
# horribly slow and 98% redundant...